[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]

[tool.pyright]
include = [
    "php5random",
]
exclude = [
    "**/__pycache__",
]
reportUnnecessaryTypeIgnoreComment = "warning"
reportUnusedImport = "error"
pythonVersion = "3.8"
typeCheckingMode = "basic"
